version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      ssh:
        - default
    volumes:
      - ../..:/workspaces:cached      
    command: sleep infinity
    environment:
      - GOPROXY=https://goproxy.cn
    networks:
      - app_net

networks:
  app_net: 
    driver: bridge